FROM denoland/deno:2.3.3
WORKDIR /app

COPY deno.json deno.lock ./
COPY apps/preview/deno.json ./apps/preview/
COPY libs/engine/deno.json ./libs/engine/

RUN deno cache --lock=deno.lock deno.json
RUN deno install --allow-scripts

COPY . .

EXPOSE 3000

CMD ["deno", "task", "dev:preview"] 
