services:
  app-development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./deno.json
    environment:
      - NODE_ENV=development
  app-production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge 
