services:
  app-development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/vendor
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
  app-production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge 
